# Generated by Django 6.0.4 on 2026-04-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0002_color_alter_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsandcompanies',
            name='category',
            field=models.ManyToManyField(related_name='category_brandspy', to='maliasStore.category', verbose_name='Категория'),
        ),
    ]
