# Generated by Django 6.0.4 on 2026-05-07 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0005_basket_city_region_remove_userrating_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitems',
            options={'verbose_name': 'Товар корзины', 'verbose_name_plural': 'Товары корзин'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_code',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.BooleanField(default=True, verbose_name='Товар новинка?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bestseller_status',
            field=models.BooleanField(default=False, verbose_name='Товар бестселлер?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maliasStore.productversion', verbose_name='Версия'),
        ),
    ]
