# Generated by Django 6.0.4 on 2026-05-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0006_alter_basketitems_options_remove_color_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Подписан(а) на рассылку?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bestseller_status',
            field=models.BooleanField(default=False, verbose_name='Бестселлер?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_status',
            field=models.BooleanField(default=True, verbose_name='Новинка?'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер получателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления доставки')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий к заказу')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('home', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом/Корпус')),
                ('flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер квартиры')),
                ('status', models.BooleanField(default=False, verbose_name='Статус доставки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maliasStore.city', verbose_name='Город')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maliasStore.customer', verbose_name='Покупатель')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maliasStore.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки пользователя',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='maliasStore.delivery', verbose_name='Доставка'),
        ),
    ]
