# Generated by Django 6.0.4 on 2026-05-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0008_remove_favourites_product_remove_favourites_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('text', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы от покупателей',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка с купона'),
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.IntegerField(default=0, verbose_name='Ваучер'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='gift',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подарочная упаковка для товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='maliasStore.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание обзора'),
        ),
    ]
