# Generated by Django 6.0.4 on 2026-05-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0009_contact_cart_coupon_discount_cart_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fax',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='postal_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Почтовый код'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='maliasStore.delivery', verbose_name='Доставка'),
        ),
    ]
