# Generated by Django 6.0.4 on 2026-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0010_delivery_company_delivery_fax_delivery_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='comment',
            new_name='comment_delivery',
        ),
        migrations.AddField(
            model_name='delivery',
            name='comment_payment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
