# Generated by Django 6.0.4 on 2026-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0011_rename_comment_delivery_comment_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
