# Generated by Django 6.0.4 on 2026-05-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0012_delivery_first_name_delivery_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='last_name',
        ),
    ]
