# Generated by Django 6.0.4 on 2026-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0013_remove_delivery_first_name_remove_delivery_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
    ]
