# Generated by Django 6.0.4 on 2026-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0014_remove_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='door_to_door',
            field=models.BooleanField(default=False, verbose_name='Доставка до двери?'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='online_payment',
            field=models.BooleanField(default=True, verbose_name='Оплата онлайн?'),
        ),
    ]
