# Generated by Django 6.0.4 on 2026-05-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0015_delivery_door_to_door_delivery_online_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='door_to_door',
            field=models.BooleanField(choices=[(True, 'Door-to-door delivery'), (False, 'Self-pickup/Post Office delivery')], default=True, verbose_name='Доставка до двери?'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='online_payment',
            field=models.BooleanField(choices=[(True, 'Online payment'), (False, 'Cash (In person)')], default=True, verbose_name='Оплата онлайн?'),
        ),
    ]
