# Generated by Django 6.0.4 on 2026-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0016_alter_delivery_door_to_door_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_est',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Примерная цена доставки'),
        ),
    ]
