# Generated by Django 6.0.4 on 2026-05-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0017_cart_delivery_est'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('slug', models.CharField(max_length=150, verbose_name='Слаг товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='В количестве')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('total_price', models.IntegerField(default=0, verbose_name='На сумму')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='maliasStore.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
    ]
