# Generated by Django 6.0.4 on 2026-05-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0018_orderproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='maliasStore.customer', verbose_name='Покупатель'),
        ),
    ]
