# Generated by Django 6.0.4 on 2026-05-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0019_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='photo',
            new_name='image',
        ),
    ]
