# Generated by Django 6.0.4 on 2026-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0020_rename_photo_orderproducts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Модель товара'),
        ),
    ]
