# Generated by Django 6.0.4 on 2026-05-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0021_orderproducts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа без скидок/доставки'),
        ),
    ]
