# Generated by Django 6.0.4 on 2026-05-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0022_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='note',
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа (без учета доставки и скидок) '),
        ),
    ]
