# Generated by Django 6.0.4 on 2026-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0023_remove_cartitems_note_alter_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка с купона'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.IntegerField(default=0, verbose_name='Ваучер'),
        ),
    ]
