# Generated by Django 6.0.4 on 2026-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0024_order_coupon_discount_order_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='version',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Версия товара'),
        ),
    ]
