# Generated by Django 6.0.4 on 2026-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maliasStore', '0026_order_delivery_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsandcompanies',
            options={'verbose_name': 'Производителя', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='brandsandcompanies',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название компании или производителя'),
        ),
    ]
